name: Create & Merge Pull Request

on:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  create_and_merge_pull_request:
    name: Create & Merge Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          github_token: ${{ secrets.GH_PAT }}
      - name: Merge Pull Request
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
